#!/bin/bash
# Auto-generated by Claude — pushes Devil Hunter to GitHub
set -e
cd "$(dirname "$0")"

echo "=== Devil Hunter → GitHub setup ==="
echo "Working in: $(pwd)"
echo

echo "[1/6] Cleaning stale .git (if any)..."
rm -rf .git

echo "[2/6] git init..."
git init -b main

echo "[3/6] Configuring user..."
git config user.email "crachad.laing@gmail.com"
git config user.name "Crach"

echo "[4/6] Staging files..."
git add -A
git status --short | head -30
echo

echo "[5/6] Creating initial commit..."
git commit -m "Initial commit: Devil Hunter game + hitbox fix

- Imported Mocha export of the game
- Fixed BattleArena hitbox bug: per-move attack ranges (MELEE_RANGE,
  DASH_IMPACT_RANGE, ENEMY_BASIC_RANGE, ENEMY_SPECIAL_RANGE,
  BLOOD_SWORD_RANGE) tuned to 80px fighter collision width
- Added .gitignore"

echo "[6/6] Adding remote + pushing..."
git remote add origin https://github.com/lennoxbain72-afk/Devil-Hunter.git
git push -u origin main

echo
echo "=== DONE — repo pushed to GitHub ==="
echo "Press any key to close this window."
read -n 1
