// Minimal stub so tsconfig.worker.json's type ref resolves.
// Originally this is generated by `wrangler types` from wrangler.json bindings.
// The worker (src/worker/index.ts) doesn't currently use any bindings.
//
// To regenerate from real bindings: `npx wrangler types`

interface Env {}
